name: CI_Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      - name: Run services
        run: docker-compose up --build -d

      - name: Wait a bit
        run: sleep 10
      - name: Check logs
        run: docker logs $(docker ps -aqf "ancestor=test-image")

      - name: Run tests
        run: poetry run pytest
