name: CI_Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      - name: Create models directory
        run: mkdir -p models
      - name: Create ML Model
        run: poetry run python ./src/california_housing_api/model_training.py

      - name: Build Docker Image
        run: docker build -t test-image .
      - name: Run Docker Container
        run: docker run -p 3000:3000 test-image

      - name: Run tests
        run: poetry run pytest
